process.env.NODE_ENV = "test";
process.env.APP_NAME = "smart-tourist-safety-backend-test";
process.env.APP_VERSION = "0.1.0-test";
process.env.HOST = "127.0.0.1";
process.env.PORT = "4001";
process.env.API_PREFIX = "/api/v1";
process.env.DATABASE_URL =
  "postgresql://postgres:postgres@127.0.0.1:5433/smart_tourist_safety_test?schema=public";
process.env.DATABASE_POOL_MAX = "2";
process.env.DATABASE_CONNECTION_TIMEOUT_MS = "500";
process.env.CORS_ORIGINS = "http://localhost:5173";
process.env.CORS_CREDENTIALS = "true";
process.env.SOCKET_IO_ENABLED = "true";
process.env.JSON_BODY_LIMIT = "1mb";
process.env.RATE_LIMIT_WINDOW_MS = "60000";
process.env.RATE_LIMIT_MAX = "1000";
process.env.TRUST_PROXY = "false";
process.env.LOG_LEVEL = "silent";
process.env.SHUTDOWN_TIMEOUT_MS = "3000";
