export const DISPATCH_STATUSES = Object.freeze({ REQUESTED:"REQUESTED", ASSIGNED:"ASSIGNED", DISPATCHED:"DISPATCHED", EN_ROUTE:"EN_ROUTE", ON_SCENE:"ON_SCENE", COMPLETED:"COMPLETED", CANCELLED:"CANCELLED" });
export const DISPATCH_STATUS_VALUES = Object.freeze(Object.values(DISPATCH_STATUSES));
