export const EMERGENCY_UNIT_STATUSES = Object.freeze({ AVAILABLE: "AVAILABLE", DISPATCHED: "DISPATCHED", OUT_OF_SERVICE: "OUT_OF_SERVICE" });
export const EMERGENCY_UNIT_STATUS_VALUES = Object.freeze(Object.values(EMERGENCY_UNIT_STATUSES));
