export const EMERGENCY_TYPES = Object.freeze({ MEDICAL: "MEDICAL", LOST: "LOST", THREAT: "THREAT", ACCIDENT: "ACCIDENT", NATURAL_DISASTER: "NATURAL_DISASTER", OTHER: "OTHER" });
export default EMERGENCY_TYPES;
