export const INCIDENT_STATUS = Object.freeze({ OPEN: "OPEN", ACKNOWLEDGED: "ACKNOWLEDGED", IN_PROGRESS: "IN_PROGRESS", RESOLVED: "RESOLVED", DISMISSED: "DISMISSED" });
export default INCIDENT_STATUS;
