/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TrustAnchor } from "./TrustAnchor";
export * as factories from "./factories";
export { TrustAnchor__factory } from "./factories/TrustAnchor__factory";
