/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TrustAnchorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "anchorConsent"
      | "anchorEvidence"
      | "anchorIncident"
      | "appendDataSnapshot"
      | "authorizeIssuer"
      | "authorizedIssuers"
      | "consentAnchoredAt"
      | "consentAnchors"
      | "evidenceAnchoredAt"
      | "evidenceAnchors"
      | "extendId"
      | "getDataSnapshot"
      | "getDataSnapshotCount"
      | "getLatestDataSnapshot"
      | "ids"
      | "incidentAnchoredAt"
      | "incidentAnchors"
      | "issueId"
      | "revokeId"
      | "revokeIssuer"
      | "verifyConsent"
      | "verifyEvidence"
      | "verifyId"
      | "verifyIncident"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsentAnchored"
      | "DataSnapshotAnchored"
      | "EvidenceAnchored"
      | "IdExtended"
      | "IdIssued"
      | "IdRevoked"
      | "IncidentAnchored"
      | "IssuerAuthorized"
      | "IssuerRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "anchorConsent",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorEvidence",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorIncident",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "appendDataSnapshot",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedIssuers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "consentAnchoredAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "consentAnchors",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceAnchoredAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evidenceAnchors",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "extendId",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDataSnapshot",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDataSnapshotCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestDataSnapshot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "ids", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "incidentAnchoredAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incidentAnchors",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueId",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeId",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyConsent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyEvidence",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "verifyId", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "verifyIncident",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "anchorConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorIncident",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appendDataSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consentAnchoredAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consentAnchors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceAnchoredAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evidenceAnchors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "extendId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDataSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDataSnapshotCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestDataSnapshot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "incidentAnchoredAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incidentAnchors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issueId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyIncident",
    data: BytesLike
  ): Result;
}

export namespace ConsentAnchoredEvent {
  export type InputTuple = [
    consentHash: BytesLike,
    actor: AddressLike,
    anchoredAt: BigNumberish,
    version: BigNumberish
  ];
  export type OutputTuple = [
    consentHash: string,
    actor: string,
    anchoredAt: bigint,
    version: bigint
  ];
  export interface OutputObject {
    consentHash: string;
    actor: string;
    anchoredAt: bigint;
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataSnapshotAnchoredEvent {
  export type InputTuple = [
    idHash: BytesLike,
    payloadHash: BytesLike,
    sequence: BigNumberish,
    snapshotType: BigNumberish,
    anchoredAt: BigNumberish,
    actor: AddressLike
  ];
  export type OutputTuple = [
    idHash: string,
    payloadHash: string,
    sequence: bigint,
    snapshotType: bigint,
    anchoredAt: bigint,
    actor: string
  ];
  export interface OutputObject {
    idHash: string;
    payloadHash: string;
    sequence: bigint;
    snapshotType: bigint;
    anchoredAt: bigint;
    actor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceAnchoredEvent {
  export type InputTuple = [
    evidenceHash: BytesLike,
    actor: AddressLike,
    anchoredAt: BigNumberish,
    version: BigNumberish
  ];
  export type OutputTuple = [
    evidenceHash: string,
    actor: string,
    anchoredAt: bigint,
    version: bigint
  ];
  export interface OutputObject {
    evidenceHash: string;
    actor: string;
    anchoredAt: bigint;
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdExtendedEvent {
  export type InputTuple = [
    idHash: BytesLike,
    previousExpiresAt: BigNumberish,
    expiresAt: BigNumberish,
    actor: AddressLike
  ];
  export type OutputTuple = [
    idHash: string,
    previousExpiresAt: bigint,
    expiresAt: bigint,
    actor: string
  ];
  export interface OutputObject {
    idHash: string;
    previousExpiresAt: bigint;
    expiresAt: bigint;
    actor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdIssuedEvent {
  export type InputTuple = [
    idHash: BytesLike,
    tripHash: BytesLike,
    issuer: AddressLike,
    issuedAt: BigNumberish,
    expiresAt: BigNumberish,
    version: BigNumberish
  ];
  export type OutputTuple = [
    idHash: string,
    tripHash: string,
    issuer: string,
    issuedAt: bigint,
    expiresAt: bigint,
    version: bigint
  ];
  export interface OutputObject {
    idHash: string;
    tripHash: string;
    issuer: string;
    issuedAt: bigint;
    expiresAt: bigint;
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdRevokedEvent {
  export type InputTuple = [
    idHash: BytesLike,
    reasonCode: BigNumberish,
    revoker: AddressLike,
    revokedAt: BigNumberish
  ];
  export type OutputTuple = [
    idHash: string,
    reasonCode: bigint,
    revoker: string,
    revokedAt: bigint
  ];
  export interface OutputObject {
    idHash: string;
    reasonCode: bigint;
    revoker: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IncidentAnchoredEvent {
  export type InputTuple = [
    incidentHash: BytesLike,
    actor: AddressLike,
    anchoredAt: BigNumberish,
    version: BigNumberish
  ];
  export type OutputTuple = [
    incidentHash: string,
    actor: string,
    anchoredAt: bigint,
    version: bigint
  ];
  export interface OutputObject {
    incidentHash: string;
    actor: string;
    anchoredAt: bigint;
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerAuthorizedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuerRevokedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): TrustAnchor;
  waitForDeployment(): Promise<this>;

  interface: TrustAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  anchorConsent: TypedContractMethod<
    [consentHash: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;

  anchorEvidence: TypedContractMethod<
    [evidenceHash: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;

  anchorIncident: TypedContractMethod<
    [incidentHash: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;

  appendDataSnapshot: TypedContractMethod<
    [
      idHash: BytesLike,
      payloadHash: BytesLike,
      encryptedPayload: BytesLike,
      sequence: BigNumberish,
      snapshotType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  authorizeIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedIssuers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  consentAnchoredAt: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  consentAnchors: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  evidenceAnchoredAt: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  evidenceAnchors: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  extendId: TypedContractMethod<
    [idHash: BytesLike, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDataSnapshot: TypedContractMethod<
    [idHash: BytesLike, index: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        payloadHash: string;
        encryptedPayload: string;
        anchoredAt: bigint;
        sequence: bigint;
        snapshotType: bigint;
      }
    ],
    "view"
  >;

  getDataSnapshotCount: TypedContractMethod<
    [idHash: BytesLike],
    [bigint],
    "view"
  >;

  getLatestDataSnapshot: TypedContractMethod<
    [idHash: BytesLike],
    [
      [string, string, bigint, bigint, bigint] & {
        payloadHash: string;
        encryptedPayload: string;
        anchoredAt: bigint;
        sequence: bigint;
        snapshotType: bigint;
      }
    ],
    "view"
  >;

  ids: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, string, bigint] & {
        tripHash: string;
        issuedAt: bigint;
        expiresAt: bigint;
        status: bigint;
        issuer: string;
        version: bigint;
      }
    ],
    "view"
  >;

  incidentAnchoredAt: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  incidentAnchors: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  issueId: TypedContractMethod<
    [
      idHash: BytesLike,
      tripHash: BytesLike,
      issuedAt: BigNumberish,
      expiresAt: BigNumberish,
      version: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  revokeId: TypedContractMethod<
    [idHash: BytesLike, reasonCode: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyConsent: TypedContractMethod<
    [consentHash: BytesLike],
    [boolean],
    "view"
  >;

  verifyEvidence: TypedContractMethod<
    [evidenceHash: BytesLike],
    [[boolean, bigint] & { exists: boolean; anchoredAt: bigint }],
    "view"
  >;

  verifyId: TypedContractMethod<
    [idHash: BytesLike],
    [
      [bigint, string, bigint, bigint, bigint] & {
        status: bigint;
        issuer: string;
        issuedAt: bigint;
        expiresAt: bigint;
        version: bigint;
      }
    ],
    "view"
  >;

  verifyIncident: TypedContractMethod<
    [incidentHash: BytesLike],
    [[boolean, bigint] & { exists: boolean; anchoredAt: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "anchorConsent"
  ): TypedContractMethod<
    [consentHash: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchorEvidence"
  ): TypedContractMethod<
    [evidenceHash: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchorIncident"
  ): TypedContractMethod<
    [incidentHash: BytesLike, version: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "appendDataSnapshot"
  ): TypedContractMethod<
    [
      idHash: BytesLike,
      payloadHash: BytesLike,
      encryptedPayload: BytesLike,
      sequence: BigNumberish,
      snapshotType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizeIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedIssuers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "consentAnchoredAt"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "consentAnchors"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "evidenceAnchoredAt"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "evidenceAnchors"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "extendId"
  ): TypedContractMethod<
    [idHash: BytesLike, expiresAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDataSnapshot"
  ): TypedContractMethod<
    [idHash: BytesLike, index: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        payloadHash: string;
        encryptedPayload: string;
        anchoredAt: bigint;
        sequence: bigint;
        snapshotType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDataSnapshotCount"
  ): TypedContractMethod<[idHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestDataSnapshot"
  ): TypedContractMethod<
    [idHash: BytesLike],
    [
      [string, string, bigint, bigint, bigint] & {
        payloadHash: string;
        encryptedPayload: string;
        anchoredAt: bigint;
        sequence: bigint;
        snapshotType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ids"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, string, bigint] & {
        tripHash: string;
        issuedAt: bigint;
        expiresAt: bigint;
        status: bigint;
        issuer: string;
        version: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "incidentAnchoredAt"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "incidentAnchors"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issueId"
  ): TypedContractMethod<
    [
      idHash: BytesLike,
      tripHash: BytesLike,
      issuedAt: BigNumberish,
      expiresAt: BigNumberish,
      version: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeId"
  ): TypedContractMethod<
    [idHash: BytesLike, reasonCode: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyConsent"
  ): TypedContractMethod<[consentHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyEvidence"
  ): TypedContractMethod<
    [evidenceHash: BytesLike],
    [[boolean, bigint] & { exists: boolean; anchoredAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyId"
  ): TypedContractMethod<
    [idHash: BytesLike],
    [
      [bigint, string, bigint, bigint, bigint] & {
        status: bigint;
        issuer: string;
        issuedAt: bigint;
        expiresAt: bigint;
        version: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyIncident"
  ): TypedContractMethod<
    [incidentHash: BytesLike],
    [[boolean, bigint] & { exists: boolean; anchoredAt: bigint }],
    "view"
  >;

  getEvent(
    key: "ConsentAnchored"
  ): TypedContractEvent<
    ConsentAnchoredEvent.InputTuple,
    ConsentAnchoredEvent.OutputTuple,
    ConsentAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "DataSnapshotAnchored"
  ): TypedContractEvent<
    DataSnapshotAnchoredEvent.InputTuple,
    DataSnapshotAnchoredEvent.OutputTuple,
    DataSnapshotAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceAnchored"
  ): TypedContractEvent<
    EvidenceAnchoredEvent.InputTuple,
    EvidenceAnchoredEvent.OutputTuple,
    EvidenceAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "IdExtended"
  ): TypedContractEvent<
    IdExtendedEvent.InputTuple,
    IdExtendedEvent.OutputTuple,
    IdExtendedEvent.OutputObject
  >;
  getEvent(
    key: "IdIssued"
  ): TypedContractEvent<
    IdIssuedEvent.InputTuple,
    IdIssuedEvent.OutputTuple,
    IdIssuedEvent.OutputObject
  >;
  getEvent(
    key: "IdRevoked"
  ): TypedContractEvent<
    IdRevokedEvent.InputTuple,
    IdRevokedEvent.OutputTuple,
    IdRevokedEvent.OutputObject
  >;
  getEvent(
    key: "IncidentAnchored"
  ): TypedContractEvent<
    IncidentAnchoredEvent.InputTuple,
    IncidentAnchoredEvent.OutputTuple,
    IncidentAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "IssuerAuthorized"
  ): TypedContractEvent<
    IssuerAuthorizedEvent.InputTuple,
    IssuerAuthorizedEvent.OutputTuple,
    IssuerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "IssuerRevoked"
  ): TypedContractEvent<
    IssuerRevokedEvent.InputTuple,
    IssuerRevokedEvent.OutputTuple,
    IssuerRevokedEvent.OutputObject
  >;

  filters: {
    "ConsentAnchored(bytes32,address,uint64,uint8)": TypedContractEvent<
      ConsentAnchoredEvent.InputTuple,
      ConsentAnchoredEvent.OutputTuple,
      ConsentAnchoredEvent.OutputObject
    >;
    ConsentAnchored: TypedContractEvent<
      ConsentAnchoredEvent.InputTuple,
      ConsentAnchoredEvent.OutputTuple,
      ConsentAnchoredEvent.OutputObject
    >;

    "DataSnapshotAnchored(bytes32,bytes32,uint32,uint8,uint64,address)": TypedContractEvent<
      DataSnapshotAnchoredEvent.InputTuple,
      DataSnapshotAnchoredEvent.OutputTuple,
      DataSnapshotAnchoredEvent.OutputObject
    >;
    DataSnapshotAnchored: TypedContractEvent<
      DataSnapshotAnchoredEvent.InputTuple,
      DataSnapshotAnchoredEvent.OutputTuple,
      DataSnapshotAnchoredEvent.OutputObject
    >;

    "EvidenceAnchored(bytes32,address,uint64,uint8)": TypedContractEvent<
      EvidenceAnchoredEvent.InputTuple,
      EvidenceAnchoredEvent.OutputTuple,
      EvidenceAnchoredEvent.OutputObject
    >;
    EvidenceAnchored: TypedContractEvent<
      EvidenceAnchoredEvent.InputTuple,
      EvidenceAnchoredEvent.OutputTuple,
      EvidenceAnchoredEvent.OutputObject
    >;

    "IdExtended(bytes32,uint64,uint64,address)": TypedContractEvent<
      IdExtendedEvent.InputTuple,
      IdExtendedEvent.OutputTuple,
      IdExtendedEvent.OutputObject
    >;
    IdExtended: TypedContractEvent<
      IdExtendedEvent.InputTuple,
      IdExtendedEvent.OutputTuple,
      IdExtendedEvent.OutputObject
    >;

    "IdIssued(bytes32,bytes32,address,uint64,uint64,uint8)": TypedContractEvent<
      IdIssuedEvent.InputTuple,
      IdIssuedEvent.OutputTuple,
      IdIssuedEvent.OutputObject
    >;
    IdIssued: TypedContractEvent<
      IdIssuedEvent.InputTuple,
      IdIssuedEvent.OutputTuple,
      IdIssuedEvent.OutputObject
    >;

    "IdRevoked(bytes32,uint8,address,uint64)": TypedContractEvent<
      IdRevokedEvent.InputTuple,
      IdRevokedEvent.OutputTuple,
      IdRevokedEvent.OutputObject
    >;
    IdRevoked: TypedContractEvent<
      IdRevokedEvent.InputTuple,
      IdRevokedEvent.OutputTuple,
      IdRevokedEvent.OutputObject
    >;

    "IncidentAnchored(bytes32,address,uint64,uint8)": TypedContractEvent<
      IncidentAnchoredEvent.InputTuple,
      IncidentAnchoredEvent.OutputTuple,
      IncidentAnchoredEvent.OutputObject
    >;
    IncidentAnchored: TypedContractEvent<
      IncidentAnchoredEvent.InputTuple,
      IncidentAnchoredEvent.OutputTuple,
      IncidentAnchoredEvent.OutputObject
    >;

    "IssuerAuthorized(address)": TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;
    IssuerAuthorized: TypedContractEvent<
      IssuerAuthorizedEvent.InputTuple,
      IssuerAuthorizedEvent.OutputTuple,
      IssuerAuthorizedEvent.OutputObject
    >;

    "IssuerRevoked(address)": TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
    IssuerRevoked: TypedContractEvent<
      IssuerRevokedEvent.InputTuple,
      IssuerRevokedEvent.OutputTuple,
      IssuerRevokedEvent.OutputObject
    >;
  };
}
