import { jest } from "@jest/globals";
import { createGroupService } from "../../src/modules/group/group.service.js";
const now=new Date("2026-08-21T10:00:00.000Z");
const baseGroup={id:"g1",tripId:"t1",leaderId:"u1",status:"ACTIVE",createdAt:now,closedAt:null,trip:{id:"t1",touristId:"u1",tripType:"GROUP",status:"PLANNED",locationName:"Prayagraj"},members:[]};
const repo=()=>({
 findTrip:jest.fn(),findGroup:jest.fn(),findGroupByTrip:jest.fn(),findActiveMembership:jest.fn(),findMembershipInTrip:jest.fn(),findOpenTripForUser:jest.fn(),createGroup:jest.fn(),createInvitation:jest.fn(),findInvitationByTokenHash:jest.fn(),revokeInvitation:jest.fn(),findInvitation:jest.fn(),joinGroup:jest.fn(),leaveGroup:jest.fn(),findMember:jest.fn(),createAudit:jest.fn().mockResolvedValue({})
});
describe("Phase 5 group service",()=>{
 test("creates a group only for an owned GROUP trip",async()=>{const r=repo();r.findTrip.mockResolvedValue({id:"t1",touristId:"u1",tripType:"GROUP",status:"PLANNED",group:null});r.createGroup.mockResolvedValue(baseGroup);const s=createGroupService({repository:r,clock:()=>now});expect((await s.createGroup("u1","t1")).id).toBe("g1");});
 test("rejects group creation for SOLO trip",async()=>{const r=repo();r.findTrip.mockResolvedValue({id:"t1",touristId:"u1",tripType:"SOLO",status:"PLANNED",group:null});const s=createGroupService({repository:r});await expect(s.createGroup("u1","t1")).rejects.toMatchObject({code:"GROUP_TRIP_REQUIRED"});});
 test("only leader can create invitation",async()=>{const r=repo();r.findGroup.mockResolvedValue({...baseGroup,leaderId:"other"});const s=createGroupService({repository:r});await expect(s.createInvitation("u1","g1",30)).rejects.toMatchObject({code:"GROUP_LEADER_REQUIRED"});});
 test("creates expiring invitation without persisting raw token",async()=>{const r=repo();r.findGroup.mockResolvedValue(baseGroup);r.createInvitation.mockImplementation((_g,d)=>Promise.resolve({id:"i1",...d}));const s=createGroupService({repository:r,clock:()=>now,tokenFactory:()=>"a".repeat(40),codeFactory:()=>"GRP-TEST"});const out=await s.createInvitation("u1","g1",30);expect(out.inviteToken).toBe("a".repeat(40));expect(r.createInvitation.mock.calls[0][1].tokenHash).not.toBe(out.inviteToken);expect(out.expiresAt.toISOString()).toBe("2026-08-21T10:30:00.000Z");});
 test("rejects expired invitation",async()=>{const r=repo();r.findInvitationByTokenHash.mockResolvedValue({id:"i1",expiresAt:new Date("2026-08-21T09:59:00Z"),revokedAt:null,group:baseGroup});const s=createGroupService({repository:r,clock:()=>now});await expect(s.joinGroup("u2","a".repeat(40))).rejects.toMatchObject({code:"INVITATION_EXPIRED"});});
 test("rejects duplicate active membership",async()=>{const r=repo();r.findInvitationByTokenHash.mockResolvedValue({id:"i1",expiresAt:new Date("2026-08-21T11:00:00Z"),revokedAt:null,group:baseGroup});r.findActiveMembership.mockResolvedValue({id:"m1"});const s=createGroupService({repository:r,clock:()=>now});await expect(s.joinGroup("u2","a".repeat(40))).rejects.toMatchObject({code:"GROUP_MEMBER_EXISTS"});});
 test("locks invitations after the trip starts",async()=>{const r=repo();r.findGroup.mockResolvedValue({...baseGroup,trip:{...baseGroup.trip,status:"ACTIVE"}});const s=createGroupService({repository:r});await expect(s.createInvitation("u1","g1",30)).rejects.toMatchObject({code:"GROUP_MEMBERSHIP_LOCKED"});});
 test("rejects joining another group while another trip is open",async()=>{const r=repo();r.findInvitationByTokenHash.mockResolvedValue({id:"i1",expiresAt:new Date("2026-08-21T11:00:00Z"),revokedAt:null,group:baseGroup});r.findActiveMembership.mockResolvedValue(null);r.findMembershipInTrip.mockResolvedValue(null);r.findOpenTripForUser.mockResolvedValue({id:"other-trip",status:"ACTIVE",locationName:"Lucknow"});const s=createGroupService({repository:r,clock:()=>now});await expect(s.joinGroup("u2","a".repeat(40))).rejects.toMatchObject({code:"CURRENT_TRIP_EXISTS"});});
 test("leader cannot leave group",async()=>{const r=repo();r.findGroup.mockResolvedValue(baseGroup);const s=createGroupService({repository:r});await expect(s.leaveGroup("u1","g1")).rejects.toMatchObject({code:"LEADER_CANNOT_LEAVE"});});
 test("non leader cannot remove members",async()=>{const r=repo();r.findGroup.mockResolvedValue({...baseGroup,leaderId:"other"});const s=createGroupService({repository:r});await expect(s.removeMember("u1","g1","m1")).rejects.toMatchObject({code:"GROUP_LEADER_REQUIRED"});});
});
