/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: "node",
  setupFiles: ["<rootDir>/tests/setup/testEnvironment.js"],
  testMatch: [
    "<rootDir>/tests/phase0/**/*.test.js",
    "<rootDir>/tests/phase1/**/*.test.js",
    "<rootDir>/tests/phase4/**/*.test.js",
    "<rootDir>/tests/phase5/**/*.test.js",
    "<rootDir>/tests/phase6/**/*.test.js",
    "<rootDir>/tests/phase7/**/*.test.js",
    "<rootDir>/tests/phase8/**/*.test.js",
    "<rootDir>/tests/phase9/**/*.test.js",
    "<rootDir>/tests/phase10/**/*.test.js",
    "<rootDir>/tests/phase11/**/*.test.js",
    "<rootDir>/tests/phase12/**/*.test.js",
    "<rootDir>/tests/phase13/**/*.test.js",
    "<rootDir>/tests/phase14/**/*.test.js",
    "<rootDir>/tests/phase15/**/*.test.js",
    "<rootDir>/tests/phase16/**/*.test.js",
    "<rootDir>/tests/phase17/**/*.test.js",
    "<rootDir>/tests/phase18/**/*.test.js",
    "<rootDir>/tests/phase19/**/*.test.js",
    "<rootDir>/tests/phase20-21/**/*.test.js",
    "<rootDir>/tests/phase22/**/*.test.js",
    "<rootDir>/tests/phase23/**/*.test.js",
  ],
  clearMocks: true,
  restoreMocks: true,
  collectCoverageFrom: [
    "src/app.js",
    "src/server.js",
    "src/common/errors/ApiError.js",
    "src/common/responses/ApiResponse.js",
    "src/common/utils/asyncHandler.js",
    "src/config/{cors,database,environment,logger,security}.js",
    "src/middleware/{errorHandler,notFound,rateLimiter,requestId}.middleware.js",
    "src/modules/health/{health.controller,health.repository,health.routes,health.service}.js",
    "src/realtime/socketServer.js",
    "src/routes/index.js",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov"],
  coverageThreshold: {
    global: {
      branches: 65,
      functions: 80,
      lines: 85,
      statements: 85,
    },
  },
  detectOpenHandles: true,
  forceExit: false,
  verbose: true,
};